#ifndef AVERRA_VERSION_H
#define AVERRA_VERSION_H

#define AVERRA_VERSION_MAJOR 1
#define AVERRA_VERSION_MINOR 0
#define AVERRA_VERSION_PATCH 0

#define AVERRA_VERSION_STR "1.0.0"

#endif // AVERRA_VERSION_H
